name = "minecolonies_official_modded"
author = "clum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59fd90bbb687dd059f5b674bebf1beddafbe297b9b289b8dc9acfc8c56a1a3c9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
