name = "minecolonies_official_modded"
author = "clum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f864f65b0c49ffa0b24e420003b1433f1e789efece245925f5276999446a5fc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
