name = "minecolonies_official_modded"
author = "clum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcd196361a92d4542a65e58b1f8c6e2f867506f46a4dd34cc659276ce288a159"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
